### ISSUE TITLE
Swipe gestures break navigation

### ISSUE THREAD

**Issue by xanderlu** [aksonov/react-native-router-flux#197]
Not sure if this is related to https://github.com/aksonov/react-native-router-flux/issues/176, since he reports a 3-50% success rate, whereas this seems to reproduce 100% of the time.

When I navigate by clicking the different links, it works fine. However, if I swipe back then try to click on a link, I get the following error:
```
No current router is set

Actions.route
Actions.js @ 44:0

Object._Actions2.default.(anonymous
Router.js @ 138:0

...
```

I cloned the repo and loaded up the Example project. Here's a .gif of the behavior:
![routerbug](https://cloud.githubusercontent.com/assets/17170343/12967658/d2cae5ac-d01d-11e5-881e-cf1f6c642bb6.gif)

**Comment by aksonov** [comment]
Yes, it is duplicate of #176. I've created issue in react-native github, because currently i don't know how to add own handler to gesture...

**Comment by lynndylanhurley** [comment]
I just created a Product Pains post for this:
https://productpains.com/post/react-native/override-swipe-back-behavior/

**Comment by lynndylanhurley** [comment]
I just pushed a fix.

**Comment by xanderlu** [comment]
Awesome! Thanks @lynndylanhurley. I might be missing something dumb&mdash;still kinda new to Redux and React Native, but after trying your PR, it looks like it's properly dispatching the actions when swiped. But, I still bump into the `No current router is set` issue.

**Comment by Elyx0** [comment]
Still bumping into the same error after a swipe

**Comment by dan-lee** [comment]
I don't think this issue should be closed, as it still occurs to me and apparently others.
Is there any way to resolve/work around this?

**Comment by aksonov** [comment]
Have you voted https://productpains.com/post/react-native/override-swipe-back-behavior/ ?

**Comment by dan-lee** [comment]
I just did so!

**Comment by aksonov** [comment]
As you can see only 6 persons were affected...

**Comment by dan-lee** [comment]
@lynndylanhurley How did you work around the error `No current router is set` with the reducer in your PR https://github.com/aksonov/react-native-router-flux/issues/204?

**Comment by kesha-antonov** [comment]
Hello guys! Is it possible now to disable swipe back gesture for some route or for all of them?

**Comment by dan-lee** [comment]
@kesha-antonov  don't have a solution for this, but we use this workaround to disable the swipe gestures for the scene configs: `Navigator.SceneConfigs.FloatFromBottom.gestures = null`

**Comment by kesha-antonov** [comment]
Cool. Thanks! @dan-lee

**Comment by aksonov** [comment]
Version 3.0 is released, but disabling swipe is not implemented but in the progress:
https://github.com/ericvicenti/navigation-rfc/issues/49

**Comment by aksonov** [comment]
Btw, 3.0 should not have problems with gesture, so feel free to create another ticket with correct title.
