### ISSUE TITLE
Viewpager has been extracted from react native core and will be removed in future

### ISSUE THREAD

**Issue by FirdousNath** [aksonov/react-native-router-flux#3485]
`<Router>
      <Lightbox>
        <Stack key="root">
          <Tabs
            hideNavBar
            key="dashboard"
            showLabel={false}
            tabBarPosition="bottom"
            activeTintColor="#c41d1d"
            inactiveTintColor="grey"
          >
            <Scene
              key="home"
              component={Home}
              title="Home"
              icon={TabIcon}
              iconName="home"
              navBar={Header}
            />
            <Scene
              tabs
              key="explore"
              tabBarPosition="top"
              tabBarStyle={{
                paddingTop: Platform.OS === "ios" ? 56 : 0,
                backgroundColor: "white"
              }}
              indicatorStyle={{ backgroundColor: "#c41d1d" }}
              showLabel={true}
              activeTintColor="#c41d1d"
              inactiveTintColor="grey"
              title="Explore"
              icon={TabIcon}
              iconName="film"
            >
              <Scene
                hideNavBar
                key="exploreTheater"
                component={() => {
                  return (
                    <View style={{ flex: 1, backgroundColor: "orange" }} />
                  );
                }}
                title="In Theathers"
              />
              <Scene
                hideNavBar
                key="exploreUpcoming"
                component={() => {
                  return (
                    <View style={{ flex: 1, backgroundColor: "yellow" }} />
                  );
                }}
                title="Upcoming"
              />
            </Scene>
            <Scene
              tabs
              key="watchlist"
              tabBarPosition="top"
              tabBarStyle={{
                paddingTop: Platform.OS === "ios" ? 56 : 0,
                backgroundColor: "white"
              }}
              indicatorStyle={{ backgroundColor: "red" }}
              showLabel={true}
              activeTintColor="#c41d1d"
              inactiveTintColor="grey"
              title="Watchlist"
              icon={TabIcon}
              iconName="bookmark"
            >
              <Scene
                hideNavBar
                key="watchlistTheater"
                component={() => {
                  return (
                    <View style={{ flex: 1, backgroundColor: "orange" }} />
                  );
                }}
                title="In Theathers"
              />
              <Scene
                hideNavBar
                key="watchlistUpcoming"
                component={() => {
                  return (
                    <View style={{ flex: 1, backgroundColor: "yellow" }} />
                  );
                }}
                title="Upcoming"
              />
            </Scene>

            <Scene
              key="profile"
              hideNavBar
              component={Home}
              title="Profile"
              icon={TabIcon}
              iconName="user"
            />
          </Tabs>
        </Stack>
        <Scene key="location" component={Location} />
      </Lightbox>
    </Router>`

**Comment by SourceCipher** [comment]
Same issue. I cant seem to find where this library is using ViewPager tho..

**Comment by chandru22** [comment]
Same issue for me also. Please solve this one

**Comment by SourceCipher** [comment]
I switched my navigation to react-navigation v3 and the issue is still there, so since this library is based on react-navigation, they probably are waiting until RN fixes it.

**Comment by FirdousNath** [comment]
Is there any way we can fix this @aksonov

**Comment by sushilnetwin** [comment]
Hey Guys, any luck with this issue? 
I am facing similar issue,  "ViewPagerAndroid has been removed from react native".

I guess react-native-router-flux should import it from react-native-viewpager now.

Please help us with this. Thanks in advance.

**Comment by KPS250** [comment]
I am using RN V0.61.3 and getting the same issue. Any update on this?

**Comment by KPS250** [comment]
Getting same issue on RN V0.61.3
Any update on this?

**Comment by mayur10** [comment]
If i use tabBarPosition="top" in <Scene tabs> or <Tabs> i get this exact error. 
react-native: 0.61.2
react-native-router-flux: 4.0.6

**Comment by michaelfemi81** [comment]
goto package.json and input     "react-native-router-flux": "^4.2.0-beta.2"
run npm install. then reset cache
or just close the packager terminal. Should fix the issue

**Comment by sushilnetwin** [comment]
When I updated the version as "react-native-router-flux": "^4.2.0-beta.2", I got the error as in screen shot.

![Screenshot_1577796051](https://user-images.githubusercontent.com/55990088/71622192-1d343300-2bfa-11ea-84b7-41aa6cf1c95f.png)

**Comment by michaelfemi81** [comment]
Reset the cache and close your terminal, then run react-native run-android

**Comment by FirdousNath** [comment]
It's almost being an year and this issue is not resolved, should we consider this library as dead ?
